//! Generate llama-server `--models-preset` INI files from GenHat `ModelDef`s.
//!
//! Each llama_server model becomes a section named exactly `def.id` so API
//! requests can use `"model": "<genhat-id>"`.

use crate::governor::HostProfile;
use crate::registry::types::{BackendKind, ModelDef};
use std::path::{Path, PathBuf};

/// Number of llama-server KV slots (`--parallel` / preset `parallel`).
/// Each chat/workspace context pins to one slot via `id_slot` so prompt caches
/// do not bleed across sessions.
pub const LLAMA_ROUTER_PARALLEL_SLOTS: u32 = 3;

/// Absolute path where we write the live router preset.
pub fn preset_path() -> PathBuf {
    if let Ok(custom) = std::env::var("GENHAT_LLAMA_PRESET_PATH") {
        return PathBuf::from(custom);
    }
    if let Some(root) = crate::paths::runtime_llama_root_opt() {
        return root.join("models-preset.ini");
    }
    std::env::temp_dir().join("genhat-models-preset.ini")
}

/// Build INI text for all llama_server models whose GGUF exists under `models_dir`.
pub fn render_preset(defs: &[ModelDef], models_dir: &Path, host: &HostProfile) -> String {
    let gov = crate::governor::Governor::new();
    let threads = host.inference_threads(gov.on_battery(), gov.thermal_pressure());
    let (batch, ubatch) = host.default_batch_sizes();
    let use_no_mmap = host.prefer_no_mmap();
    let use_mlock = host.prefer_mlock();
    let parallel = LLAMA_ROUTER_PARALLEL_SLOTS;

    let mut out = String::new();
    out.push_str("# Auto-generated by GenHat — do not edit by hand.\n");
    out.push_str("version = 1\n\n");
    out.push_str("[*]\n");
    out.push_str(&format!("threads = {threads}\n"));
    out.push_str(&format!("threads-batch = {threads}\n"));
    out.push_str(&format!("parallel = {parallel}\n"));
    // Disable similarity-based auto slot picking — GenHat assigns id_slot explicitly.
    out.push_str("slot-prompt-similarity = 0\n");
    out.push_str("fit = off\n");
    out.push_str(&format!("batch-size = {batch}\n"));
    out.push_str(&format!("ubatch-size = {ubatch}\n"));
    if use_no_mmap {
        out.push_str("no-mmap = true\n");
    }
    out.push('\n');

    let mut any = false;
    for def in defs {
        if def.backend != BackendKind::LlamaServer {
            continue;
        }
        let model_path = models_dir.join(&def.model_file);
        if !model_path.is_file() {
            log::debug!(
                "Skipping preset for '{}': missing {}",
                def.id,
                model_path.display()
            );
            continue;
        }
        any = true;
        out.push_str(&format!("[{}]\n", def.id));
        out.push_str(&format!("model = {}\n", path_for_ini(&model_path)));

        if let Some(ctx) = def.params.get("ctx_size") {
            // llama-server splits -c across --parallel slots. Scale so each slot
            // keeps approximately the model's configured context window.
            if let Ok(per_slot) = ctx.parse::<u32>() {
                let total = per_slot.saturating_mul(parallel).max(per_slot);
                out.push_str(&format!("ctx-size = {total}\n"));
            } else {
                out.push_str(&format!("ctx-size = {ctx}\n"));
            }
        }
        if let Some(n) = def.params.get("max_tokens") {
            out.push_str(&format!("n-predict = {n}\n"));
        }
        if let Some(t) = def.params.get("temp") {
            out.push_str(&format!("temp = {t}\n"));
        }
        if let Some(p) = def.params.get("top_p") {
            out.push_str(&format!("top-p = {p}\n"));
        }
        if let Some(k) = def.params.get("top_k") {
            out.push_str(&format!("top-k = {k}\n"));
        }
        if let Some(r) = def.params.get("repeat_penalty") {
            out.push_str(&format!("repeat-penalty = {r}\n"));
        }
        if def.params.get("flash_attn").map(|v| is_truthy(v)).unwrap_or(false) {
            out.push_str("flash-attn = enabled\n");
        }
        if def.params.get("mlock").map(|v| is_truthy(v)).unwrap_or(false) && use_mlock {
            out.push_str("mlock = true\n");
        }
        if let Some(ct) = def.params.get("cache_type") {
            if !ct.is_empty() {
                out.push_str(&format!("cache-type-k = {ct}\n"));
                out.push_str(&format!("cache-type-v = {ct}\n"));
            }
        }
        if def.params.get("embedding").map(|v| is_truthy(v)).unwrap_or(false) {
            out.push_str("embedding = true\n");
            let bs = def
                .params
                .get("batch_size")
                .cloned()
                .unwrap_or_else(|| batch.to_string());
            out.push_str(&format!("batch-size = {bs}\n"));
        }
        if let Some(kwargs) = def.params.get("chat_template_kwargs") {
            if !kwargs.is_empty() {
                // INI values with braces/quotes stay as a single line.
                out.push_str(&format!("chat-template-kwargs = {kwargs}\n"));
            }
        }
        // Do not load every model at router start — demand-load on first request.
        out.push_str("load-on-startup = false\n");
        out.push('\n');
    }

    if !any {
        log::warn!("Router preset has no models — no GGUF files found under {}", models_dir.display());
    }
    out
}

/// Write the preset for `defs` and return its path + content hash (for change detection).
pub fn write_preset(defs: &[ModelDef], models_dir: &Path) -> Result<(PathBuf, u64), String> {
    let host = HostProfile::detect();
    let content = render_preset(defs, models_dir, &host);
    let path = preset_path();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create preset dir {}: {e}", parent.display()))?;
    }
    std::fs::write(&path, &content)
        .map_err(|e| format!("Failed to write preset {}: {e}", path.display()))?;
    let hash = hash_bytes(content.as_bytes());
    log::info!(
        "Wrote llama-server models-preset ({} bytes, hash={hash:#x}) → {}",
        content.len(),
        path.display()
    );
    Ok((path, hash))
}

fn path_for_ini(path: &Path) -> String {
    // Absolute paths avoid CWD ambiguity; escape is unnecessary for our GGUF paths.
    path.canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .to_string_lossy()
        .to_string()
}

fn is_truthy(value: &str) -> bool {
    matches!(
        value.trim().to_ascii_lowercase().as_str(),
        "1" | "true" | "yes" | "on" | "enabled"
    )
}

fn hash_bytes(bytes: &[u8]) -> u64 {
    // Simple FNV-1a 64 — enough for preset change detection, no extra deps.
    let mut hash: u64 = 0xcbf29ce484222325;
    for b in bytes {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::types::{ModelKind, TaskType};
    use std::collections::HashMap;

    fn sample_def(id: &str, file: &str, embedding: bool) -> ModelDef {
        let mut params = HashMap::new();
        params.insert("ctx_size".into(), "4096".into());
        params.insert("temp".into(), "0.7".into());
        params.insert("flash_attn".into(), "true".into());
        if embedding {
            params.insert("embedding".into(), "true".into());
        }
        ModelDef {
            id: id.into(),
            name: id.into(),
            backend: BackendKind::LlamaServer,
            kind: ModelKind::ChildProcess,
            model_file: file.into(),
            tasks: if embedding {
                vec![TaskType::Embed]
            } else {
                vec![TaskType::Chat]
            },
            auto_start: false,
            max_instances: 1,
            idle_timeout_s: 300,
            priority: 10,
            memory_mb: 500,
            gdrive_id: None,
            is_zip: false,
            hf_repo: None,
            hf_file: None,
            hf_files: HashMap::new(),
            params,
            task_priorities: HashMap::new(),
        }
    }

    #[test]
    fn render_preset_sections_use_model_ids() {
        let dir = tempfile::tempdir().expect("tempdir");
        let chat = dir.path().join("chat.gguf");
        let emb = dir.path().join("emb.gguf");
        std::fs::write(&chat, b"gguf").unwrap();
        std::fs::write(&emb, b"gguf").unwrap();

        let defs = vec![
            sample_def("qwen-test", "chat.gguf", false),
            sample_def("bge-test", "emb.gguf", true),
            sample_def("missing", "nope.gguf", false),
        ];
        let host = HostProfile::synthetic(8, 16, 16 * 1024, 8 * 1024);
        let ini = render_preset(&defs, dir.path(), &host);

        assert!(ini.contains("[qwen-test]"));
        assert!(ini.contains("[bge-test]"));
        assert!(!ini.contains("[missing]"));
        assert!(ini.contains("embedding = true"));
        assert!(ini.contains("ctx-size = 12288"));
        assert!(ini.contains("load-on-startup = false"));
        assert!(ini.contains("parallel = 3"));
        assert!(ini.contains("slot-prompt-similarity = 0"));
        assert!(ini.contains("fit = off"));
    }
}
