//! Functional Schema Library — the operation vocabulary for MCP tools.
//!
//! The SLM emits compact plans using these types (constrained by GBNF grammars).
//! MCP tools then interpret them deterministically — no free-form code, no
//! hallucinated formulas, no guessed sums. Native code does the heavy lifting
//! (revamp.md §1.1 "SLM Routes, Native Computes").

use serde::{Deserialize, Serialize};

// ─────────────────────────────────────────────────────────────────────────────
// Spreadsheet Schema
// ─────────────────────────────────────────────────────────────────────────────

/// A single spreadsheet operation from the functional vocabulary.
///
/// These are the *only* operations the SLM may emit for spreadsheet synthesis.
/// The `mcp-server-excel` binary interprets them with native Rust code.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "op")]
pub enum SpreadsheetOp {
    /// Sum all values in the named column.
    #[serde(rename = "SUM_COLUMN")]
    SumColumn {
        col: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },

    /// Average values in `value_col`, grouped by `group_col`.
    #[serde(rename = "AVERAGE_BY_GROUP")]
    AverageByGroup {
        value_col: String,
        group_col: String,
    },

    /// Create a pivot table using row/column/value dimensions.
    #[serde(rename = "PIVOT")]
    Pivot {
        row_col: String,
        col_col: String,
        value_col: String,
    },

    /// Sort the sheet descending by the named column.
    #[serde(rename = "SORT_DESC")]
    SortDesc { col: String },

    /// Sort the sheet ascending by the named column.
    #[serde(rename = "SORT_ASC")]
    SortAsc { col: String },

    /// Keep only rows where `col` equals `value`.
    #[serde(rename = "FILTER_ROWS")]
    FilterRows { col: String, value: String },

    /// Count occurrences per unique value in `group_col`.
    #[serde(rename = "COUNT_BY_GROUP")]
    CountByGroup { group_col: String },

    /// Add a computed column using a simple arithmetic `formula` string.
    /// Formula references other column names by exact string match.
    #[serde(rename = "ADD_COLUMN")]
    AddColumn { name: String, formula: String },

    /// Write raw data rows with headers to the worksheet.
    /// Used when the model needs to generate data inline (e.g., from general knowledge)
    /// or supplement existing attached data. Works with or without an attached file.
    #[serde(rename = "WRITE_DATA")]
    WriteData {
        headers: Vec<String>,
        rows: Vec<Vec<String>>,
    },

    /// Rename the active worksheet.
    #[serde(rename = "RENAME_SHEET")]
    RenameSheet { name: String },
}

/// A complete spreadsheet synthesis plan emitted by the SLM.
/// Sent to `mcp-server-excel` as the JSON-RPC request payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpreadsheetPlan {
    /// Sequence of operations to apply to the data, in order.
    pub ops: Vec<SpreadsheetOp>,

    /// Source data rows (CSV format, injected by the MCP coordinator from the
    /// file the user referenced; not generated by the SLM).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_rows: Option<Vec<Vec<String>>>,

    /// Column headers for the source data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<String>>,

    /// Optional output filename hint (without extension).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_name: Option<String>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Presentation Schema
// ─────────────────────────────────────────────────────────────────────────────

/// Approved slide layout types for `mcp-server-presentation`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SlideLayout {
    Title,
    Bullet,
    TwoColumn,
    ImageLeft,
    Blank,
    Section,
    Stat,
    Quote,
    Cards,
    Comparison,
    Centered,
}

/// A bundled image for offline embedding in HTML / presentation artifacts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArtifactImageAsset {
    pub data_uri: String,
    #[serde(default)]
    pub caption: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub alt: Option<String>,
}

/// A single slide in a presentation plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresentationSlide {
    pub title: String,
    pub layout: SlideLayout,
    #[serde(default)]
    pub bullets: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Index into `PresentationPlan::images` for IMAGE_LEFT (and similar) layouts.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_index: Option<u32>,
    /// Left column heading for COMPARISON slides.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub left_title: Option<String>,
    /// Right column heading for COMPARISON slides.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub right_title: Option<String>,
}

/// A complete presentation synthesis plan emitted by the SLM.
/// Sent to `mcp-server-presentation` as the JSON-RPC request payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresentationPlan {
    pub slides: Vec<PresentationSlide>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_name: Option<String>,
    /// Embedded images (data URIs) referenced by slide `image_index`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<ArtifactImageAsset>>,
}

/// A complete HTML synthesis plan emitted by the SLM.
/// Sent to `mcp-server-html` as the JSON-RPC request payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HtmlPlan {
    #[serde(default)]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tagline: Option<String>,
    #[serde(default = "default_html_archetype")]
    pub archetype: String,
    #[serde(default)]
    pub sections: Vec<HtmlSection>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_name: Option<String>,
    /// Legacy raw-HTML plans (used only when `sections` is empty).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    /// Tabular source rows (first row may be headers when `headers` is absent).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_rows: Option<Vec<Vec<String>>>,
    /// Column headers for `source_rows`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<String>>,
    /// Embedded images (data URIs) referenced by section `image_index`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<ArtifactImageAsset>>,
}

fn default_html_archetype() -> String {
    "landing".to_string()
}

/// Section kinds understood by the HTML renderer.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum HtmlSectionKind {
    Hero,
    InfoBar,
    Grid,
    Split,
    Stats,
    Quotes,
    Faq,
    Cta,
    Text,
    Chart,
    Image,
}

/// One content block in a page plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HtmlSection {
    pub kind: HtmlSectionKind,
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(default)]
    pub items: Vec<HtmlSectionItem>,
    /// Chart variant when `kind` is `CHART`: `bar`, `pie`, or `line`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chart_type: Option<String>,
    /// Source column for category labels (file-backed dashboards).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label_column: Option<String>,
    /// Source column for numeric values (file-backed dashboards).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value_column: Option<String>,
    /// Aggregation over duplicate labels: `sum`, `count`, `avg`, `min`, `max`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aggregation: Option<String>,
    /// Index into `HtmlPlan::images` for IMAGE sections / hero visuals.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_index: Option<u32>,
}

impl HtmlSection {
    pub fn with_kind(kind: HtmlSectionKind) -> Self {
        Self {
            kind,
            title: String::new(),
            subtitle: None,
            body: None,
            items: vec![],
            chart_type: None,
            label_column: None,
            value_column: None,
            aggregation: None,
            image_index: None,
        }
    }
}

/// Row/card item inside a section (menu item, feature, FAQ, stat, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HtmlSectionItem {
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<String>,
}

// ─────────────────────────────────────────────────────────────────────────────
// Schema Manifest
// ─────────────────────────────────────────────────────────────────────────────

/// A schema manifest descriptor loaded from `config/manifests/*.json`.
///
/// Binds an intent to a tool, GBNF grammar, and token budget.
/// The `schema_contract_version` must match the version embedded in any GGUF
/// model header (revamp.md §12).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaManifest {
    pub intent: String,
    pub schema_contract_version: String,
    pub tool: String,
    pub gbnf: String,
    pub max_plan_tokens: u32,
}

impl SchemaManifest {
    /// Load the built-in manifest for the given intent name.
    ///
    /// Manifests are embedded at compile time via `include_str!` so they are
    /// always available without filesystem access in production.
    pub fn load(intent: &str) -> Result<Self, String> {
        match intent {
            "spreadsheet_synthesis" => serde_json::from_str(include_str!(
                "../config/manifests/spreadsheet_synthesis.json"
            ))
            .map_err(|e| format!("Failed to parse spreadsheet_synthesis manifest: {e}")),

            "presentation_synthesis" => serde_json::from_str(include_str!(
                "../config/manifests/presentation_synthesis.json"
            ))
            .map_err(|e| format!("Failed to parse presentation_synthesis manifest: {e}")),

            "html_synthesis" => serde_json::from_str(include_str!(
                "../config/manifests/html_synthesis.json"
            ))
            .map_err(|e| format!("Failed to parse html_synthesis manifest: {e}")),

            other => Err(format!("Unknown schema manifest: '{other}'")),
        }
    }
}
